 INSERT INTO public.dog_breed (id, name, image_src, name_en) VALUES (47, 'Бобтейл', null, 'Old English Sheepdog (Bobtail)'),
 (60, 'Бородатий коллі', null, 'Bearded Collie'),
 (71, 'Англійський спрингер-спаніель', null, 'English Springer Spaniel'),
 (68, 'Кокер-спаніель-американець', null, 'Cocker Spaniel-American'),
 (42, 'Гордон Сеттер', null, 'Gordon Setter'),
 (145, 'Манчестер той терʼєр', null, 'Manchester Terrier (Toy)'),
 (108, 'Бостонський тер''єр', null, 'Boston Terrier'),
 (144, 'Мальтійська', null, 'Maltese'),
 (146, 'Папільйон', null, 'Papillon'),
 (138, 'Уіппет', null, 'Whippet'),
 (85, 'Плотт-хаунд', null, 'Plott Hound'),
 (147, 'Померанська', null, 'Pomeranian'),
 (114, 'Такса', null, 'Dachshund'),
 (110, 'Керн-тер''єр', null, 'Cairn Terrier'),
 (111, 'Кардиган вельш-коргі', null, 'Cardigan Welsh Corgi'),
 (119, 'Французький бульдог', null, 'French Bulldog'),
 (142, 'Італійська хорт', null, 'Italian Greyhound'),
 (96, 'Сассекський спаніель', null, 'Sussex Spaniel'),
 (128, 'Шотландський тер’єр', null, 'Scottish Terrier'),
 (86, 'Пойнтер', null, 'Pointer'),
 (95, 'Шнауцер', null, 'Standard Schnauzer'),
 (106, 'Вельш тер’єр', null, 'Welsh Terrier'),
 (118, 'Фокс терʼєр жорсткошерстний', null, 'Fox Terrier ��� Wirehair'),
 (98, 'Вельш-Спрінгер-спаніель', null, 'Welsh Springer Spaniel'),
 (94, 'Стаффордширський бультер''єр', null, 'Staffordshire Bull Terrier'),
 (87, 'Польська низова вівчарка', null, 'Polish Lowland Sheepdog'),
 (131, 'Шиба Іну', null, 'Shiba Inu'),
 (149, 'Той-фокстерʼєр', null, 'Toy Fox Terrier'),
 (123, 'Манчестер терʼєр', null, 'Manchester Terrier (Standard)'),
 (117, 'Фокс терʼєр гладкий', null, 'Fox Terrier ��� Smooth'),
 (141, 'Китайська хохлата', null, 'Chinese Crested'),
 (18, 'Афганська гонча', null, 'Afghan Hound'),
 (3, 'Бернський зенненхунд', null, 'Bernese Mountain Dog'),
 (14, 'Ньюфаундленд', null, 'Newfoundland'),
 (4, 'Бладхаунд', null, 'Bloodhound'),
 (13, 'Неаполітанський мастиф', null, 'Neopolitan Mastiff'),
 (11, 'Куваш', null, 'Kuvasz'),
 (7, 'Дог', null, 'Great Dane'),
 (22, 'Малінуа', null, 'Belgian Malinois'),
 (20, 'Американський фоксхаунд', null, 'American Foxhound'),
 (21, 'Босерон', null, 'Beauceron'),
 (37, 'Німецька вівчарка', 'https://pbs.twimg.com/profile_images/3268703988/0e0a5d44905c7d420cbb93e599c83120.jpeg', 'German Shepherd Dog'),
 (31, 'Кламбер-спаніель', null, 'Clumber Spaniel'),
 (24, 'Тервурен', null, 'Belgian Tervuren'),
 (35, 'Англійський Фоксхаунд', null, 'English Foxhound'),
 (29, 'Бріард', null, 'Briard'),
 (36, 'Англійський сетер', null, 'English Setter'),
 (26, 'Чорний російський тер''єр', null, 'Black Russian Terrier'),
 (23, 'Бельгійська вівчарка', null, 'Belgian Sheepdog'),
 (38, 'Німецький короткошерстий пойнтер ', null, 'German Shorthaired Pointer'),
 (33, 'Кучерявий ретрівер', null, 'Curly Coated Retriever'),
 (28, 'Боксер', null, 'Boxer'),
 (34, 'Доберман-пінчер', null, 'Doberman Pinscher'),
 (46, 'Лабрадор ретрівер', null, 'Labrador Retriever'),
 (41, 'Золотистий ретривер', null, 'Golden Retriever'),
 (44, 'Ірландський сетер', null, 'Irish Setter'),
 (66, 'Китайський шарпей', null, 'Chinese Shar Pei'),
 (25, 'Black And Tan Coonhound', null, 'Black And Tan Coonhound'),
 (65, 'Ханаанська собака', null, 'Canaan Dog'),
 (67, 'Чау-чау', null, 'Chow Chow'),
 (59, 'Бассет-хаунд', null, 'Basset Hound'),
 (16, 'Ротвейлер', 'https://pbs.twimg.com/profile_images/2758979518/b29f6da5d411aefa4a7eda51f4d5d20d.jpeg', 'Rottweiler'),
 (69, 'Кокер-спаніель-англійська', null, 'Cocker Spaniel-English'),
 (49, 'Родезійський риджбек', null, 'Rhodesian Ridgeback'),
 (58, 'Австралійська вівчарка', null, 'Australian Shepherd'),
 (48, 'Пудель', null, 'Poodle Standard'),
 (54, 'Ердейл тер’єр', null, 'Airdale Terrier'),
 (70, 'Далматин', null, 'Dalmatian'),
 (43, 'Хорт', null, 'Greyhound'),
 (61, 'Бордер-коллі', null, 'Border Collie'),
 (50, 'Шотландський Дірхаунд', null, 'Scottish Deerhound'),
 (45, 'Комондор', null, 'Komondor'),
 (64, 'Бультер''єр', null, 'Bull Terrier'),
 (55, 'Американський стаффордшир', null, 'American Staffordshire Terrier'),
 (52, 'Тибетський мастиф', null, 'Tibetan Mastiff'),
 (15, 'Оттерхаунд', null, 'Otter Hound'),
 (27, 'Фландрский бувье', null, 'Bouvier Des Flandres'),
 (30, 'Чесапик-бей-ретривер', null, 'Chesapeake Bay Retriever'),
 (116, 'Англійський той-спаніель', null, 'English Toy Spaniel'),
 (140, 'Чихуахуа', 'https://pbs.twimg.com/profile_images/611066126697525249/hxwreQDl_400x400.jpg', 'Chihuahua'),
 (57, 'Австралійський скотар', null, 'Australian Cattle Dog'),
 (79, 'Кеесхонд', null, 'Keeshond'),
 (53, 'Веймаранер', null, 'Weimaraner'),
 (76, 'Ібіцька гонча', null, 'Ibizan Hound'),
 (78, 'Ірдандський водяний спаніель', null, 'Irish Water Spaniel'),
 (75, 'Харʼєр', null, 'Harrier'),
 (9, 'Зенненхунд', null, 'Great Swiss Mountain Dog'),
 (39, 'Дратхаар', null, 'German Wirehaired Pointer'),
 (88, 'Португальска водяний дог', null, 'Portuguese Water Dog'),
 (84, 'Фараонова собака', null, 'Pharaoh Hound'),
 (77, 'Ірландський тер’єр', null, 'Irish Terrier'),
 (72, 'Польовий спаніель', null, 'Field Spaniel'),
 (74, 'Фінський шпіц', null, 'Finnish Spitz'),
 (80, 'Керрі-блю-тер’єр', null, 'Kerry Blue Terrier'),
 (92, 'Сибірський хаскі', null, 'Siberian Husky'),
 (109, 'Брюссельський Гріфон', null, 'Brussels Griffon'),
 (124, 'Пудель мініатюрний', null, 'Poodle Miniature'),
 (135, 'Тибетський спаніель', null, 'Tibetan Spaniel'),
 (91, 'Самоїд', null, 'Samoyed'),
 (90, 'Салюкі', null, 'Saluki'),
 (133, 'Шовковистий тер’єр', null, 'Silky Terrier'),
 (148, 'Той пудель', null, 'Poodle Toy'),
 (120, 'Німецький пінчер', null, 'German Pinscher'),
 (125, 'Мопс', null, 'Pug'),
 (137, 'Вест-Хайленд-Уайт-тер''єр', null, 'West Highland White Terrier'),
 (136, 'Тибетський тер’єр', null, 'Tibetan Terrier'),
 (139, 'Аффенпінчер', null, 'Affenpinscher'),
 (81, 'Норвезький Елькхаунд', null, 'Norwegian Elkhound'),
 (105, 'Бішон Фріз', null, 'Bichon Frise'),
 (101, 'Австралійський тер''єр', null, 'Australian Terrier'),
 (107, 'Бордер тер’єр', null, 'Border Terrier'),
 (132, 'Ши-тцу', null, 'Shih Tzu'),
 (130, 'Шетландська вівчарка', null, 'Shetland Sheepdog (Sheltie)'),
 (1, 'Акіта', 'https://cdn140.picsart.com/234020305012212.png?type=webp&to=crop&r=256', 'Akita'),
 (10, 'Ірландський вовкодав', 'https://pbs.twimg.com/profile_images/2648405167/fa6ba6afef95db13ee864d65fc4e6748.jpeg', 'Irish Wolfhound'),
 (150, 'Йоркширський тер’єр', 'https://pbs.twimg.com/profile_images/2686904641/6798aec028c5f8f44da1cb521fde8aa7.jpeg', 'Yorkshire Terrier'),
 (6, 'Бульмастиф', 'https://pbs.twimg.com/profile_images/3261858980/82a12f1899fb8b7124971b46d4513a14.jpeg', 'Bullmastiff'),
 (2, 'Анатолійська вівчарка', 'https://i.pinimg.com/originals/06/19/46/0619469a7936f07cb0192d0c011c06b1.jpg', 'Anatolian Sheepdog'),
 (12, 'Мастиф', 'https://s.cafebazaar.ir/1/icons/com.dogsimulator.mastiff-5fb299eb-962d-4b21-902a-6c636fe94387_128x128.webp', 'Mastiff'),
 (5, 'Борза', 'https://images.pexels.com/users/avatars/20194713/karolina-wv-184.jpeg?auto=compress&fit=crop&h=256&w=256', 'Borzoi'),
 (17, 'Сенбернар', 'https://obessia.com/images/breeds/thumbnails/queen.jpg', 'Saint Bernard'),
 (8, 'Піренейська', null, 'Great Pyrenees'),
 (32, 'Короткошерстий коллі', null, 'Collie (Rough) & (Smooth)'),
 (112, 'Кавалер кінг-чарльз-спаниель', null, 'Cavalier King Charles Spaniel'),
 (113, 'Котон-де-тулеар', null, 'Coton de Tulear'),
 (104, 'Бедлінгтон терʼєр', null, 'Bedlington Terrier'),
 (115, 'Денді дінмонт терʼєр', null, 'Dandie Dinmont Terrier'),
 (143, 'Японський хін', null, 'Japanese Chin'),
 (103, 'Бігль', 'https://pbs.twimg.com/profile_images/378800000525976301/fcea4cf6e423ec58670b1688c2bfba06.jpeg', 'Beagle'),
 (102, 'Басенджі', null, 'Basenji'),
 (126, 'Пулі', null, 'Puli'),
 (100, 'Ескімо', null, 'American Eskimo'),
 (89, 'Червоний кунхаунд', null, 'Redbone Coonhound'),
 (63, 'Бульдог', 'https://pbs.twimg.com/profile_images/739658360614707202/gGWc6aiy_400x400.jpg', 'Bull Dog'),
 (134, 'Скайтер''єр', null, 'Skye Terrier'),
 (73, 'Гладкошерстий ретривер', null, 'Flat Coated Retriever'),
 (40, 'Різеншнауцер', null, 'Giant Schnauzer'),
 (56, 'Американський водяний спаніель', null, 'American Water Spaniel'),
 (127, 'Шиперке', null, 'Schipperke'),
 (62, 'Брітані', null, 'Brittany'),
 (122, 'Лейкленд-терʼєр', null, 'Lakeland Terrier'),
 (99, 'Грифон Кортальса', null, 'Wirehaired Pointing Griffon'),
 (97, 'Вижла', null, 'Vizsla'),
 (51, 'Спінон', null, 'Spinone Italiano'),
 (121, 'Глен оф Імал терʼєр', null, 'Glen Imaal Terrier'),
 (129, 'Сіліхем-терʼєр', null, 'Sealyham Terrier'),
 (82, 'Новошотландський ретривер', null, 'Nova Scotia Duck Tolling Retriever'),
 (83, 'Вандейський бассет-грифон', null, 'Petit Basset Griffon Vendeen'),
 (93, 'Ірландський мʼякошерстий', null, 'Soft-Coated Wheaten Terrier'),
 (19, 'Маламут', 'https://styles.redditmedia.com/t5_2a80lt/styles/communityIcon_6q8hic7bojo41.png?width=256&s=c9ac713303500b49d4874eadf5529cfb39cd653a', 'Alaskan Malamute');
